[package]
name = "sndio-sys"
description = "Bindings for OpenBSD's sndio."
license = "MIT"
version = "0.0.1"
authors = ["Michael Killough <michaeljkillough@gmail.com>"]
edition = "2018"

[build-dependencies]
bindgen = "0.53"

[dependencies]
libc = "0.2"

